FROM golang:1.24-alpine

WORKDIR /app

COPY shared/ ./shared/
COPY services/token/go.mod services/token/go.sum ./

RUN mkdir -p ../../shared && cp -r ./shared/* ../../shared/

COPY services/token/ ./

RUN go mod download
RUN go mod tidy

CMD ["go", "test", "-v", "./tests/..."]