version: "2"

run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gocyclo
    - revive
    - unparam
    - godot
  disable: []
  exclusions:
    rules:
      - path: tests/mocks/.*\.go
        linters:
          - errcheck
          - govet
          - staticcheck
          - gocyclo
          - revive
          - unparam
          - godot
      - path: services/subscription/internal/adapter/http/subscription_handler.go
        linters:
          - errcheck
  settings:
    errcheck:
      check-type-assertions: true
      ignore: "github.com/gin-gonic/gin.(*Context).JSON,github.com/gin-gonic/gin.(*Context).Data"
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: unexported-return
          severity: warning
        - name: var-naming
          severity: error
        - name: blank-imports
          severity: error
    unparam:
      check-exported: true
    godot:
      scope: all

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      print-linter-name: false
      print-issued-lines: false
      colors: false