services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: weather_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d weather_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
    depends_on:
      postgres-test:
        condition: service_healthy

volumes:
  postgres_test_data: 