services:
  postgres-integration:
    image: postgres:15
    environment:
      POSTGRES_DB: weather_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d weather_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-e2e:
    image: postgres:15
    environment:
      POSTGRES_DB: weather_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d weather_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_integration_data:
  postgres_e2e_data: 