FROM golang:1.24-alpine

WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.mod
COPY go.sum go.sum

# Download dependencies
RUN go mod download

# Copy source code
COPY . ./

# Run tests
CMD ["go", "test", "-v", "./tests/..."] 