// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/email/email.proto

package email

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeatherUpdateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	To               string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject          string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	City             string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Temperature      int32                  `protobuf:"varint,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity         int32                  `protobuf:"varint,7,opt,name=humidity,proto3" json:"humidity,omitempty"`
	WindSpeed        int32                  `protobuf:"varint,8,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	UnsubscribeToken string                 `protobuf:"bytes,9,opt,name=unsubscribe_token,json=unsubscribeToken,proto3" json:"unsubscribe_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WeatherUpdateRequest) Reset() {
	*x = WeatherUpdateRequest{}
	mi := &file_proto_email_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherUpdateRequest) ProtoMessage() {}

func (x *WeatherUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherUpdateRequest.ProtoReflect.Descriptor instead.
func (*WeatherUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherUpdateRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *WeatherUpdateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *WeatherUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WeatherUpdateRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *WeatherUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WeatherUpdateRequest) GetTemperature() int32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *WeatherUpdateRequest) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *WeatherUpdateRequest) GetWindSpeed() int32 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *WeatherUpdateRequest) GetUnsubscribeToken() string {
	if x != nil {
		return x.UnsubscribeToken
	}
	return ""
}

type EmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailResponse) Reset() {
	*x = EmailResponse{}
	mi := &file_proto_email_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailResponse) ProtoMessage() {}

func (x *EmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailResponse.ProtoReflect.Descriptor instead.
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{1}
}

func (x *EmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EmailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_email_email_proto protoreflect.FileDescriptor

const file_proto_email_email_proto_rawDesc = "" +
	"\n" +
	"\x17proto/email/email.proto\x12\x05email\"\x94\x02\n" +
	"\x14WeatherUpdateRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x05R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\a \x01(\x05R\bhumidity\x12\x1d\n" +
	"\n" +
	"wind_speed\x18\b \x01(\x05R\twindSpeed\x12+\n" +
	"\x11unsubscribe_token\x18\t \x01(\tR\x10unsubscribeToken\"Y\n" +
	"\rEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2V\n" +
	"\fEmailService\x12F\n" +
	"\x11SendWeatherUpdate\x12\x1b.email.WeatherUpdateRequest\x1a\x14.email.EmailResponseB\x1fZ\x1dweather-broadcast/proto/emailb\x06proto3"

var (
	file_proto_email_email_proto_rawDescOnce sync.Once
	file_proto_email_email_proto_rawDescData []byte
)

func file_proto_email_email_proto_rawDescGZIP() []byte {
	file_proto_email_email_proto_rawDescOnce.Do(func() {
		file_proto_email_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_email_email_proto_rawDesc), len(file_proto_email_email_proto_rawDesc)))
	})
	return file_proto_email_email_proto_rawDescData
}

var file_proto_email_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_email_email_proto_goTypes = []any{
	(*WeatherUpdateRequest)(nil), // 0: email.WeatherUpdateRequest
	(*EmailResponse)(nil),        // 1: email.EmailResponse
}
var file_proto_email_email_proto_depIdxs = []int32{
	0, // 0: email.EmailService.SendWeatherUpdate:input_type -> email.WeatherUpdateRequest
	1, // 1: email.EmailService.SendWeatherUpdate:output_type -> email.EmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_email_email_proto_init() }
func file_proto_email_email_proto_init() {
	if File_proto_email_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_email_email_proto_rawDesc), len(file_proto_email_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_email_email_proto_goTypes,
		DependencyIndexes: file_proto_email_email_proto_depIdxs,
		MessageInfos:      file_proto_email_email_proto_msgTypes,
	}.Build()
	File_proto_email_email_proto = out.File
	file_proto_email_email_proto_goTypes = nil
	file_proto_email_email_proto_depIdxs = nil
}
