global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'weather-api'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 5s
    scrape_timeout: 5s