FROM golang:1.24-alpine

WORKDIR /app

# Copy go.mod and go.sum files
COPY go.work go.work
COPY services/email/go.mod services/email/go.mod
COPY services/email/go.sum services/email/go.sum

# Download dependencies
RUN go work sync

# Copy source code
COPY services/email/ ./services/email/

# Run tests
CMD ["go", "test", "-v", "./tests/..."] 