// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/subscription/subscription.proto

package subscription

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListByFrequencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frequency     string                 `protobuf:"bytes,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	LastId        int32                  `protobuf:"varint,2,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByFrequencyRequest) Reset() {
	*x = ListByFrequencyRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByFrequencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByFrequencyRequest) ProtoMessage() {}

func (x *ListByFrequencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByFrequencyRequest.ProtoReflect.Descriptor instead.
func (*ListByFrequencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *ListByFrequencyRequest) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *ListByFrequencyRequest) GetLastId() int32 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ListByFrequencyRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListByFrequencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	LastIndex     int32                  `protobuf:"varint,2,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByFrequencyResponse) Reset() {
	*x = ListByFrequencyResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByFrequencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByFrequencyResponse) ProtoMessage() {}

func (x *ListByFrequencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByFrequencyResponse.ProtoReflect.Descriptor instead.
func (*ListByFrequencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *ListByFrequencyResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *ListByFrequencyResponse) GetLastIndex() int32 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Frequency     string                 `protobuf:"bytes,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Confirmed     bool                   `protobuf:"varint,5,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *Subscription) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Subscription) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Subscription) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Subscription) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *Subscription) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *Subscription) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_proto_subscription_subscription_proto protoreflect.FileDescriptor

const file_proto_subscription_subscription_proto_rawDesc = "" +
	"\n" +
	"%proto/subscription/subscription.proto\x12\fsubscription\"l\n" +
	"\x16ListByFrequencyRequest\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\tR\tfrequency\x12\x17\n" +
	"\alast_id\x18\x02 \x01(\x05R\x06lastId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"z\n" +
	"\x17ListByFrequencyResponse\x12@\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1a.subscription.SubscriptionR\rsubscriptions\x12\x1d\n" +
	"\n" +
	"last_index\x18\x02 \x01(\x05R\tlastIndex\"\x9a\x01\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x1c\n" +
	"\tfrequency\x18\x04 \x01(\tR\tfrequency\x12\x1c\n" +
	"\tconfirmed\x18\x05 \x01(\bR\tconfirmed\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token2u\n" +
	"\x13SubscriptionService\x12^\n" +
	"\x0fListByFrequency\x12$.subscription.ListByFrequencyRequest\x1a%.subscription.ListByFrequencyResponseB&Z$weather-broadcast/proto/subscriptionb\x06proto3"

var (
	file_proto_subscription_subscription_proto_rawDescOnce sync.Once
	file_proto_subscription_subscription_proto_rawDescData []byte
)

func file_proto_subscription_subscription_proto_rawDescGZIP() []byte {
	file_proto_subscription_subscription_proto_rawDescOnce.Do(func() {
		file_proto_subscription_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subscription_subscription_proto_rawDesc), len(file_proto_subscription_subscription_proto_rawDesc)))
	})
	return file_proto_subscription_subscription_proto_rawDescData
}

var file_proto_subscription_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_subscription_subscription_proto_goTypes = []any{
	(*ListByFrequencyRequest)(nil),  // 0: subscription.ListByFrequencyRequest
	(*ListByFrequencyResponse)(nil), // 1: subscription.ListByFrequencyResponse
	(*Subscription)(nil),            // 2: subscription.Subscription
}
var file_proto_subscription_subscription_proto_depIdxs = []int32{
	2, // 0: subscription.ListByFrequencyResponse.subscriptions:type_name -> subscription.Subscription
	0, // 1: subscription.SubscriptionService.ListByFrequency:input_type -> subscription.ListByFrequencyRequest
	1, // 2: subscription.SubscriptionService.ListByFrequency:output_type -> subscription.ListByFrequencyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_subscription_subscription_proto_init() }
func file_proto_subscription_subscription_proto_init() {
	if File_proto_subscription_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subscription_subscription_proto_rawDesc), len(file_proto_subscription_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subscription_subscription_proto_goTypes,
		DependencyIndexes: file_proto_subscription_subscription_proto_depIdxs,
		MessageInfos:      file_proto_subscription_subscription_proto_msgTypes,
	}.Build()
	File_proto_subscription_subscription_proto = out.File
	file_proto_subscription_subscription_proto_goTypes = nil
	file_proto_subscription_subscription_proto_depIdxs = nil
}
