FROM golang:1.24-alpine

WORKDIR /app

# Copy go.mod and go.sum files
COPY go.work go.work
COPY services/weather-broadcast/go.mod services/weather-broadcast/go.mod
COPY services/weather-broadcast/go.sum services/weather-broadcast/go.sum

# Download dependencies
RUN go work sync

# Copy source code
COPY services/weather-broadcast/ ./services/weather-broadcast/

# Run tests
CMD ["go", "test", "-v", "./tests/..."] 