name: golangci-lint
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [email, subscription, token, weather, weather-broadcast]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run golangci-lint for ${{ matrix.service }}
        working-directory: ./services/${{ matrix.service }}
        run: |
          go mod download
          golangci-lint run --timeout=5m