name: Lint

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    name: Lint All Services
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Run Linter for All Services
      run: |
        for service in email subscription token weather-broadcast; do
          echo "Running linter for $service service..."
          cd services/$service
          golangci-lint run --config=../../.golangci.yaml --skip-dirs="tests/mocks/*,mocks/*"
          cd ../..
        done 