name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - run: go mod download

      - uses: golangci/golangci-lint-action@v6
        with:
            version: v1.64.8
            args: --timeout=5m --out-format=colored-line-number
            config: .golangci.yml

      - run: go build -v ./...

      - run: go test -v ./...