name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  email-service-tests:
    name: Email Service Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go Environment
      uses: ./.github/actions/setup
    
    - name: Start MailHog
      run: docker run -d --name mailhog -p 1025:1025 -p 8025:8025 mailhog/mailhog:latest
    
    - name: Wait for MailHog
      run: sleep 5
    
    - name: Run Email Service Tests
      env:
        GO111MODULE: on
        GOMOD: ${{ github.workspace }}/services/email/go.mod
      run: |
        cd services/email
        go test -v ./tests/...

  subscription-service-tests:
    name: Subscription Service Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go Environment
      uses: ./.github/actions/setup
    
    - name: Start PostgreSQL
      run: |
        docker run -d --name postgres-subscription \
          -e POSTGRES_DB=subscription_test \
          -e POSTGRES_USER=test \
          -e POSTGRES_PASSWORD=test \
          -p 5432:5432 \
          postgres:15
    
    - name: Start MailHog
      run: docker run -d --name mailhog-subscription -p 1026:1025 -p 8026:8025 mailhog/mailhog:latest
    
    - name: Wait for services
      run: sleep 10
    
    - name: Run Subscription Service Tests
      env:
        GO111MODULE: on
        GOMOD: ${{ github.workspace }}/services/subscription/go.mod
      run: |
        cd services/subscription
        go test -v ./tests/...

  token-service-tests:
    name: Token Service Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go Environment
      uses: ./.github/actions/setup
    
    - name: Run Token Service Tests
      env:
        GO111MODULE: on
        GOMOD: ${{ github.workspace }}/services/token/go.mod
      run: |
        cd services/token
        go test -v ./tests/...

  weather-broadcast-service-tests:
    name: Weather Broadcast Service Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go Environment
      uses: ./.github/actions/setup
    
    - name: Run Weather Broadcast Service Tests
      env:
        GO111MODULE: on
        GOMOD: ${{ github.workspace }}/services/weather-broadcast/go.mod
      run: |
        cd services/weather-broadcast
        go test -v ./tests/...