name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  service-tests:
    name: Service Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [email, subscription, token, weather-broadcast]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go Environment
      uses: ./.github/actions/setup
    
    - name: Start PostgreSQL (for services that need it)
      if: matrix.service == 'subscription' || matrix.service == 'weather-broadcast'
      run: |
        docker run -d --name postgres-${{ matrix.service }} \
          -e POSTGRES_DB=${matrix.service}_test \
          -e POSTGRES_USER=test \
          -e POSTGRES_PASSWORD=test \
          -p 5432:5432 \
          postgres:15
    
    - name: Start MailHog (for services that need it)
      if: matrix.service == 'email' || matrix.service == 'subscription' || matrix.service == 'weather-broadcast'
      run: |
        docker run -d --name mailhog-${{ matrix.service }} \
          -p 1025:1025 \
          -p 8025:8025 \
          mailhog/mailhog:latest
    
    - name: Wait for services
      if: matrix.service == 'subscription' || matrix.service == 'weather-broadcast'
      run: sleep 10
    
    - name: Move project into GOPATH
      run: |
        mkdir -p ~/go/src/${{ matrix.service }}
        cp -r services/${{ matrix.service }}/* ~/go/src/${{ matrix.service }}/
        cd ~/go/src/${{ matrix.service }}
        go test -v ./tests/...