name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  all-service-tests:
    name: All Service Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go Environment
      uses: ./.github/actions/setup
    
    - name: Start PostgreSQL
      run: |
        docker run -d --name postgres-subscription \
          -e POSTGRES_DB=subscription_test \
          -e POSTGRES_USER=test \
          -e POSTGRES_PASSWORD=test \
          -p 5432:5432 \
          postgres:15
    
    - name: Start MailHog
      run: docker run -d --name mailhog -p 1025:1025 -p 8025:8025 mailhog/mailhog:latest
    
    - name: Wait for services
      run: sleep 10
    
    - name: Run All Service Tests
      env:
        GO111MODULE: on
      run: |
        go work sync
        GOMOD=${{ github.workspace }}/services/email/go.mod cd services/email && go test -v ./tests/...
        GOMOD=${{ github.workspace }}/services/subscription/go.mod cd services/subscription && go test -v ./tests/...
        GOMOD=${{ github.workspace }}/services/token/go.mod cd services/token && go test -v ./tests/...
        GOMOD=${{ github.workspace }}/services/weather-broadcast/go.mod cd services/weather-broadcast && go test -v ./tests/...